  graph LR
  subgraph SanctuarySystem["C_SanctuarySystem"]
    TWI((O_TWI)) --> PIO((O_PIO))
    PIO --> UARL((O_UARL))
    UARL --> EWSO((O_EWSO))
    EWSO --> Egregore((O_Egregore))
    Egregore --> SanctuaryRevolution((O_SanctuaryRevolution))
  end

  subgraph OntologyEngineering["C_OntologyEngineering"]
    TRANSPO((O_TRANSPO)) --> SemOntoRel((O_SemOntoRel))
    SemOntoRel --> KnowledgeRepresentation((O_KnowledgeRepresentation))
    KnowledgeRepresentation --> InformationSystems((O_InformationSystems))
  end

  subgraph CognitiveProcesses["C_CognitiveProcesses"]
    SkillChains((O_SkillChains)) --> EmergentThinking((O_EmergentThinking))
    EmergentThinking --> DunningKrugerEffect((O_DunningKrugerEffect))
    DunningKrugerEffect --> Learning((O_Learning)) 
  end 

  subgraph AIandLLMs["C_AIandLLMs"]
    DUO((O_DUO)) --> PromptEngineering((O_PromptEngineering))
    PromptEngineering --> LLMCapabilities((O_LLMCapabilities))
    LLMCapabilities --> AIethics((O_AIethics))
  end

  PIO --> TRANSPO --> f_PIOtoUARL
  EWSO --> TRANSPO --> f_EWSOtoTRANSPO
  SkillChains --> LLMCapabilities --> f_SkillChainstoLLMCapabilities
  CognitiveProcesses --> AIethics --> f_CognitiveProcessestoAIethics

  subgraph "Latent Spaces"
    L_TWI --> L_O_TWI
    L_PIO --> L_O_PIO
  end

  SanctuarySystem --> AIandLLMs --> F_SanctuarySystemToAIethics
  OntologyEngineering --> InformationSystems --> F_OntologyEngineeringToKnowledgeRepresentation
